version: '3.9'
services:
  web:
    env_file: .env
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./credentials/gemini-service-key.json:/tmp/gemini-service-key.json 
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS_B64=...     # as before
      - DJANGO_SECRET_KEY=...
      - DEBUG=1
    command: gunicorn online_judge.wsgi:application --bind 0.0.0.0:8000
