version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./credentials/gemini-service-key.json:/tmp/gemini-service-key.json 
    environment:
      - DEBUG=1
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gemini-service-key.json 
