# Generated by Django 5.1.6 on 2025-06-01 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='problem',
            name='test_cases_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_format',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_format',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
