# Generated by Django 5.1.6 on 2025-06-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contest_contestannouncement_contestparticipant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='duration',
            field=models.DurationField(blank=True, help_text='Contest duration (e.g., 2:00:00 for 2 hours)', null=True),
        ),
    ]
