# Generated by Django 5.1.6 on 2025-06-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsubmission',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='verdict',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
