# Generated by Django 5.1.6 on 2025-06-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contestsubmission_score_contestsubmission_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
