# Generated by Django 5.1.6 on 2025-08-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_problem_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("setter", "Problem Setter"),
                    ("participant", "Participant"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
