# Generated by Django 5.1.6 on 2025-08-09 13:51

import core.utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile photo (max 5MB, JPG/PNG/GIF/WEBP)",
                null=True,
                upload_to=core.utils.file_validators.get_upload_path,
                validators=[core.utils.file_validators.validate_image_file],
            ),
        ),
    ]
